### ISSUE TITLE
add busybox for debugging purposes

### ISSUE THREAD

**Issue by developer-guy** [chainguard-images/static#17]
Like google's distroless image, they provide a version of _busybox_ included, and they served it through another tag called _:debug_ [^1]. We (w/@dentrax) thought we could do the same for the static image. 

We are willing to do this by creating another workflow for the debug version of the static image.

[^1]: https://github.com/GoogleContainerTools/distroless/blob/dc517ebfe22cf7d4ee02b44b21e443f96aaaa364/base/base.bzl#L65-L74

**Comment by imjasonh** [comment]
If you want busybox, you can just use busybox (`cgr.dev/chainguard/busybox`). I don't think we want to add a tag that fundamentally changes what's in the image.
